version: '3'
services:
  nginx:
    container_name: nginx-test-gin
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/app
    depends_on:
      - app

  app:
    container_name: app-test-gin
    build:
      context: .docker/go
      dockerfile: Dockerfile
    environment:
      PORT: '8080'
    volumes:
      - ./src/:/go/src/app
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-test-gin
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gin_development
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - database:/var/lib/mysql
      - ./.docker/db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  database: